export {U24}
export default class U24 {
  public _id: string;
  public _rev: string;
  public "@xp_skirmish": number;
  public "@nb_tank_bought":number;
  public "@ELO_LB_value":number;
  public "@nb_reco_bought":number;
  public "@gametype_conquest":number;
  public "@nb_veh_bought":number;
  public "@multi_draw":number;
  public "@campaign_last_game":number;
  public "@ELO_LB_delta_value":number;
  public "@ranked_nato":number;
  public "@xp_campaign":number;
  public "@xp_multi":number;
  public "@level":number;
  public "@total_unit_bought":number;
  public "@time_skirmish_played":number;
  public "@xp_ranked":number;
  public "@tactic_nato":number;
  public "@nb_log_bought":number;
  public "@multi_nato":number;
  public "@multi_win":number;
  public "@nb_air_bought":number;
  public "@ELO":number;
  public "@nb_sup_bought":number;
  public "@nb_naval_bought":number;
  public "@time_campaign_played":number;
  public "@ranked_loss":number;
  public "@multi_last_game":number;
  public "@campaign_nato":number;
  public "@tactic_nato_win":number;
  public "@ELO_LB_rank":number;
  public "@time_ranked_played":number;
  public "@gametype_dest":number;
  public "@multi_loss":number;
  public "@multi_played":number;
  public "@time_multi_played":number;
  public "@campaign_wins":number;
  public "@nb_inf_bought":number;
  public "@ranked_last_game":number;
  public "@nb_hel_bought":number;
  public "@ELO_LB_delta_rank":number;
  public "@multi_pact":number;
  constructor(obj:any) {
    this._id = <string>obj["_id"];
    this._rev = <string>obj["_rev"];
    this["@xp_skirmish"] = parseInt(<string>obj["@xp_skirmish"]);
    this["@nb_tank_bought"] = parseInt(<string>obj["@"]);
    this["@ELO_LB_value"] = parseInt(<string>obj["@"]);
    this["@nb_reco_bought"] = parseInt(<string>obj["@"]);
    this["@gametype_conquest"] = parseInt(<string>obj["@"]);
    this["@nb_veh_bought"] = parseInt(<string>obj["@"]);
    this["@multi_draw"] = parseInt(<string>obj["@"]);
    this["@campaign_last_game"] = parseInt(<string>obj["@"]);
    this["@ELO_LB_delta_value"] = parseInt(<string>obj["@"]);
    this["@ranked_nato"] = parseInt(<string>obj["@"]);
    this["@xp_campaign"] = parseInt(<string>obj["@"]);
    this["@xp_multi"] = parseInt(<string>obj["@"]);
    this["@level"] = parseInt(<string>obj["@"]);
    this["@total_unit_bought"] = parseInt(<string>obj["@"]);
    this["@time_skirmish_played"] = parseInt(<string>obj["@"]);
    this["@xp_ranked"] = parseInt(<string>obj["@"]);
    this["@tactic_nato"] = parseInt(<string>obj["@"]);
    this["@nb_log_bought"] = parseInt(<string>obj["@"]);
    this["@multi_nato"] = parseInt(<string>obj["@"]);
    this["@multi_win"] = parseInt(<string>obj["@"]);
    this["@nb_air_bought"] = parseInt(<string>obj["@"]);
    this["@ELO"] = parseInt(<string>obj["@"]);
    this["@nb_sup_bought"] = parseInt(<string>obj["@"]);
    this["@nb_naval_bought"] = parseInt(<string>obj["@"]);
    this["@time_campaign_played"] = parseInt(<string>obj["@"]);
    this["@ranked_loss"] = parseInt(<string>obj["@"]);
    this["@multi_last_game"] = parseInt(<string>obj["@"]);
    this["@campaign_nato"] = parseInt(<string>obj["@"]);
    this["@tactic_nato_win"] = parseInt(<string>obj["@"]);
    this["@ELO_LB_rank"] = parseInt(<string>obj["@"]);
    this["@time_ranked_played"] = parseInt(<string>obj["@"]);
    this["@gametype_dest"] = parseInt(<string>obj["@"]);
    this["@multi_loss"] = parseInt(<string>obj["@"]);
    this["@multi_played"] = parseInt(<string>obj["@"]);
    this["@time_multi_played"] = parseInt(<string>obj["@"]);
    this["@campaign_wins"] = parseInt(<string>obj["@"]);
    this["@nb_inf_bought"] = parseInt(<string>obj["@"]);
    this["@ranked_last_game"] = parseInt(<string>obj["@"]);
    this["@nb_hel_bought"] = parseInt(<string>obj["@"]);
    this["@ELO_LB_delta_rank"] = parseInt(<string>obj["@"]);
    this["@multi_pact"] = parseInt(<string>obj["@"]);
  }
}